### PR TITLE
feat: Enable a few more newer Node.js rules

### PR DESCRIPTION
**Pull request by XhmikosR**
🎉 Thanks for sending this pull request! 🎉

Please make sure the title is clear and descriptive.

If you are fixing a typo or documentation, please skip these instructions.

Otherwise please fill in the sections below.

**Which problem is this pull request solving?**

Example: I'm always frustrated when [...]

**List other issues or pull requests related to this problem**

Example: This fixes #5012

**Describe the solution you've chosen**

Example: I've fixed this by [...]

**Describe alternatives you've considered**

Example: Another solution would be [...]

**Checklist**

Please add a `x` inside each checkbox:

- [x] I have read the [contribution guidelines](../blob/main/CONTRIBUTING.md).
- [x] The status checks are successful (continuous integration). Those can be seen below.

### CODE REVIEW

**Comment by XhmikosR** [comment]
These are the changes on the cli repo: https://github.com/netlify/cli/compare/main...XhmikosR:test-eslint

`unicorn/prefer-object-from-entries` might be good to enable too, but not all cases are auto-fixable.

**Comment by XhmikosR** [comment]
Let me know how do you want to proceed with `unicorn/prefer-object-from-entries`. Maybe we should land this as is and cut a new version and then try to enable `unicorn/prefer-object-from-entries`?

**Comment by ehmicky** [comment]
Thanks a lot @XhmikosR!

About `Object.fromEntries()`, I believe the ESLint Unicorn rule is unfortunately too strict when it comes to some legitimate usage of `Array.reduce()` as you mention, so I would personally not favor enabling this specific rule.

**Review by ehmicky — APPROVED** [review]

**Comment by ascorbic** [comment]
In future, can updates that enable new rules be treated as breaking changes and released as a new major version?

**Comment by ehmicky** [comment]
Absolutely. Sorry, and thanks for the reminder @ascorbic :pray:

**Comment by ascorbic** [comment]
Thanks!

**Pull request merged**
