### PR TITLE
fix!: use `eslint-plugin-n` instead of `eslint-plugin-node`

### PR DESCRIPTION
**Pull request by ehmicky**
See https://github.com/netlify/eslint-config-node/pull/321#issuecomment-1035222089

`eslint-plugin-node` is unmaintained and `eslint-plugin-n` is a maintained fork.
This will allow us to upgrade to ESLint v8.

**Checklist**

Please add a `x` inside each checkbox:

- [x] I have read the [contribution guidelines](../blob/main/CONTRIBUTING.md).
- [x] The status checks are successful (continuous integration). Those can be seen below.

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]
I'm assuming this is breaking change for this library if we need to rename rules in consumers?

Can we merge with `fix!: ...`?

**Comment by ehmicky** [comment]
Right, great call @erezrokah!

**Comment by erezrokah** [comment]
This was a breaking change, but not in the way we expected? https://github.com/netlify/cli/runs/5791278004?check_suite_focus=true#step:7:17

**Comment by ehmicky** [comment]
Re-building `package-lock.json` fixes it.
Also any references to `eslint-plugin-node` (in `.eslintrc.*` or as `eslint-disable` comments) must be renamed to `eslint-plugin-n`.

**Pull request merged**
